---
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
pre_build_script:
- cp docker/Dockerfile .
script:
- echo "Build SUNET Custom ARGUS-Fronted Image"
builders:
- docker
docker_name: sunet/argus-frontend-test
docker_tags:
- "v1.14.1_sunetbuild"
