---
git:
  branch: main
triggers:
  # cron: "@daily"
  github_push: true
clean_workspace: true
pre_build_script:
- cp docker/Dockerfile .
script:
- echo "Build SUNET Custom ARGUS-Fronted Image"
builders:
- docker
docker_name: sunet/argus-frontend
docker_tags:
- "v1.14.1_sunetbuild"
docker_no_cache: true
docker_force_tag: true
docker_build_args: |
  BRANCH_NAME=v1.14.1
  REPO_URL=https://github.com/Uninett/Argus-frontend.git
